/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.tynne.schrumpf.ui;

import de.tynne.schrumpf.business.FormatBean;

/**
 *
 * @author Stephan Fuhrmann <stephan@tynne.de>
 */
public class FormatPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormatPanel
     */
    public FormatPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jCheckBoxChange = new javax.swing.JCheckBox();
        jComboBoxFileFormat = new javax.swing.JComboBox();
        jLabelFileFormat = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/tynne/schrumpf/ui/FormatPanel"); // NOI18N
        setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FormatPanel.border.title"))); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        jCheckBoxChange.setText(bundle.getString("FormatPanel.jCheckBoxChange.text")); // NOI18N
        jCheckBoxChange.setToolTipText(bundle.getString("FormatPanel.jCheckBoxChange.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jCheckBoxChange, gridBagConstraints);

        String formatNames[] = javax.imageio.ImageIO.getWriterFormatNames();
        jComboBoxFileFormat.setModel(new javax.swing.DefaultComboBoxModel(formatNames));
        jComboBoxFileFormat.setToolTipText(bundle.getString("FormatPanel.jComboBoxFileFormat.toolTipText")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jCheckBoxChange, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jComboBoxFileFormat, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jComboBoxFileFormat, gridBagConstraints);

        jLabelFileFormat.setText(bundle.getString("FormatPanel.jLabelFileFormat.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(jLabelFileFormat, gridBagConstraints);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxChange;
    private javax.swing.JComboBox jComboBoxFileFormat;
    private javax.swing.JLabel jLabelFileFormat;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public FormatBean toBean() {
        FormatBean bean = new FormatBean();
        bean.setChange(jCheckBoxChange.isSelected());
        bean.setFileFormatName((String)jComboBoxFileFormat.getSelectedItem());
        return bean;
    }
}
