

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  maven_version:
    uses: sfuhrm/github_workflows/.github/workflows/maven-expression.yml@main
    permissions:
      contents: read
    with:
      java_version: 21
      expression: project.version
  call-workflow-passing-data:
    needs: maven_version
    uses: sfuhrm/github_workflows/.github/workflows/maven.yml@main
    permissions:
      contents: read
    with:
      java_version: "[ \"21\" ]"
      artifact_name: build
      artifact_path: target/*.jar
  sign:
    needs: call-workflow-passing-data
    permissions:
      contents: read
    runs-on: ubuntu-latest    
    steps:
    - name: Download build
      uses: actions/download-artifact@v4.1.7
      with:
        name: build

    - uses: sfuhrm/gpg-sign-action@main
      with:
        gpg-key: foobar
        gpg-passphrase: foobar
        input-path: build

    - uses: actions/upload-artifact@v4
      with:
        name: build2
        path: "build/**"
